serviceName="OPCUAKafkaProxy"

mode="consumer" # producer、consumer

enableProd=false

showContent = true

[LOGGER]
	level= 1 # 0=trace;1=debug;2=info;3=warn;4=error;5=critical
	outdir="logs/OPCUAKafkaProxy-Logs"

[DEV]
brokers="172.31.254.89:9092,172.31.254.89:9096,172.31.254.89:9097"
topics=["test-topic-1","test-topic-2","test-topic-3","test-topic-4","test-topic-5","test-topic-6","test-topic-7","test-topic-8","test-topic-9","test-topic-10","test-topic-11","test-topic-12","test-topic-13","test-topic-14","test-topic-15","test-topic-16","test-topic-17","test-topic-18","test-topic-19","test-topic-20"]
groupId="xt-iot"
saslUsername=""
saslPassword=""
sslCaLocation=""
sslKeyLocation=""
sslCertificateLocation=""
securityProtocol="" #SASL_SSL
saslMechanism="" #PLAIN, SCRAM-SHA-256, SCRAM-SHA-512
sslEndpointIdentificationAlgorithm="" # none, https

[PROD]
brokers="10.11.22.91:9092" #10.11.22.91:9092 #172.31.254.86:9092
topics=[
	"FTP-TEST-TOPIC-1",
	"FTP-TEST-TOPIC-2",
#	"IOT_ZHU_YUN_SHU_XI_TONG_N01_02",
#	"IOT_ZHU_YUN_SHU_XI_TONG_N03",
#	"IOT_ZHU_YUN_SHU_XI_TONG_N04",
#	"IOT_ZHU_YUN_SHU_XI_TONG_N05",
#	"IOT_VFD_N03",
#	"IOT_VFD_N04",
#	"IOT_VFD_N05"
	]
#groupId="jx-collector"
groupId="xt-iot"
saslUsername="iot_receive"
saslPassword="Metaworks@123"
sslCaLocation="D:/work/cpp_work/OPCUAProxy/cer/kafka-trust.crt"
sslKeyLocation=""
sslCertificateLocation=""
securityProtocol="SASL_SSL" #SASL_SSL
saslMechanism="PLAIN" #PLAIN, SCRAM-SHA-256, SCRAM-SHA-512
sslEndpointIdentificationAlgorithm="none" # none, https